### ISSUE TITLE
Compiler warning 

### ISSUE THREAD

**Issue by daviddelmonte** [blaszku/MediaPresenterFramework#1]
Hi. Great control! Many thanks!!

I am seeing this message in the console when running the example: `Cannot be called with asCopy = NO on non-main thread.`

**Comment by baquaz** [comment]
Thanks for your feedback. I forgot to perform presenting pickers from main thread. I'll update the code.

Anyway I am struggling with warning/error while dismissing picker.
Everything works as expected, but the warning appears like it's unresolved yet by current swift version or Apple - dunno, tried everything.
More info:
[Stack](https://stackoverflow.com/questions/44465904/photopicker-discovery-error-error-domain-pluginkit-code-13)
[Apple forum](https://forums.developer.apple.com/thread/82105)
